/**
 * RARE 4N - Complete Themes System (50+ Themes)
 * ???????? ?????????????? ???????????? - 50+ ??????
 */

import { Theme } from './themes';

// Generate 50+ themes from backend library
export const ALL_THEMES: Theme[] = [
  // Cyber & Neon Themes (5)
  {
    id: 'cyber-neon',
    name: 'Cyber Neon',
    nameAr: '?????????? ????????',
    primary: '#00eaff',
    secondary: '#ff00ff',
    accent: '#00d4e6',
    background: ['#000408', '#001820', '#000408'],
    surface: '#001820',
    text: '#ffffff',
    textSecondary: '#00eaff',
    border: '#00eaff',
    cardStyle: 'glass',
    buttonStyle: '3d-glow',
    borderGlow: true,
    blur: 10,
    iconStyle: 'filled',
    iconColor: '#00eaff',
    fontFamily: 'System',
    fontSize: { xs: 10, sm: 12, base: 14, md: 16, lg: 18, xl: 20, '2xl': 24, '3xl': 32 },
  },
  {
    id: 'neon-purple',
    name: 'Neon Purple',
    nameAr: '???????? ????????????',
    primary: '#a855f7',
    secondary: '#ec4899',
    accent: '#9333ea',
    background: ['#0a0a0f', '#1a0a2e', '#0a0a0f'],
    surface: '#1a0a2e',
    text: '#ffffff',
    textSecondary: '#a855f7',
    border: '#a855f7',
    cardStyle: 'glass',
    buttonStyle: '3d-glow',
    borderGlow: true,
    blur: 10,
    iconStyle: 'filled',
    iconColor: '#a855f7',
    fontFamily: 'System',
    fontSize: { xs: 10, sm: 12, base: 14, md: 16, lg: 18, xl: 20, '2xl': 24, '3xl': 32 },
  },
  {
    id: 'neon-green',
    name: 'Neon Green',
    nameAr: '???????? ????????',
    primary: '#00ff88',
    secondary: '#00d4ff',
    accent: '#00cc6a',
    background: ['#000a0a', '#001a0a', '#000a0a'],
    surface: '#001a0a',
    text: '#ffffff',
    textSecondary: '#00ff88',
    border: '#00ff88',
    cardStyle: 'glass',
    buttonStyle: '3d-glow',
    borderGlow: true,
    blur: 10,
    iconStyle: 'filled',
    iconColor: '#00ff88',
    fontFamily: 'System',
    fontSize: { xs: 10, sm: 12, base: 14, md: 16, lg: 18, xl: 20, '2xl': 24, '3xl': 32 },
  },
  {
    id: 'neon-blue',
    name: 'Neon Blue',
    nameAr: '???????? ????????',
    primary: '#00d4ff',
    secondary: '#0099ff',
    accent: '#00b8e6',
    background: ['#000a14', '#001428', '#000a14'],
    surface: '#001428',
    text: '#ffffff',
    textSecondary: '#00d4ff',
    border: '#00d4ff',
    cardStyle: 'glass',
    buttonStyle: '3d-glow',
    borderGlow: true,
    blur: 10,
    iconStyle: 'filled',
    iconColor: '#00d4ff',
    fontFamily: 'System',
    fontSize: { xs: 10, sm: 12, base: 14, md: 16, lg: 18, xl: 20, '2xl': 24, '3xl': 32 },
  },
  {
    id: 'neon-red',
    name: 'Neon Red',
    nameAr: '???????? ????????',
    primary: '#ff0040',
    secondary: '#ff6b00',
    accent: '#cc0033',
    background: ['#0a0000', '#1a0000', '#0a0000'],
    surface: '#1a0000',
    text: '#ffffff',
    textSecondary: '#ff0040',
    border: '#ff0040',
    cardStyle: 'glass',
    buttonStyle: '3d-glow',
    borderGlow: true,
    blur: 10,
    iconStyle: 'filled',
    iconColor: '#ff0040',
    fontFamily: 'System',
    fontSize: { xs: 10, sm: 12, base: 14, md: 16, lg: 18, xl: 20, '2xl': 24, '3xl': 32 },
  },
  
  // Glass & Modern Themes (4)
  {
    id: 'glass-morphism',
    name: 'Glass Morphism',
    nameAr: '?????????? ????????',
    primary: '#ffffff',
    secondary: '#a855f7',
    accent: '#e0e0e0',
    background: ['#f0f0f0', '#e0e0e0', '#f0f0f0'],
    surface: 'rgba(255, 255, 255, 0.1)',
    text: '#000000',
    textSecondary: '#666666',
    border: 'rgba(255, 255, 255, 0.2)',
    cardStyle: 'glass',
    buttonStyle: 'flat',
    borderGlow: false,
    blur: 20,
    iconStyle: 'filled',
    iconColor: '#a855f7',
    fontFamily: 'System',
    fontSize: { xs: 10, sm: 12, base: 14, md: 16, lg: 18, xl: 20, '2xl': 24, '3xl': 32 },
  },
  {
    id: 'frosted-glass',
    name: 'Frosted Glass',
    nameAr: '???????? ??????????',
    primary: '#ffffff',
    secondary: '#cbd5e1',
    accent: '#e2e8f0',
    background: ['#f8fafc', '#f1f5f9', '#f8fafc'],
    surface: 'rgba(255, 255, 255, 0.15)',
    text: '#1e293b',
    textSecondary: '#64748b',
    border: 'rgba(255, 255, 255, 0.3)',
    cardStyle: 'glass',
    buttonStyle: 'flat',
    borderGlow: false,
    blur: 30,
    iconStyle: 'outline',
    iconColor: '#64748b',
    fontFamily: 'System',
    fontSize: { xs: 10, sm: 12, base: 14, md: 16, lg: 18, xl: 20, '2xl': 24, '3xl': 32 },
  },
  {
    id: 'modern-minimal',
    name: 'Modern Minimal',
    nameAr: '???????? ????????',
    primary: '#000000',
    secondary: '#666666',
    accent: '#333333',
    background: ['#ffffff', '#f5f5f5', '#ffffff'],
    surface: '#ffffff',
    text: '#000000',
    textSecondary: '#666666',
    border: '#e0e0e0',
    cardStyle: 'solid',
    buttonStyle: 'flat',
    borderGlow: false,
    blur: 0,
    iconStyle: 'outline',
    iconColor: '#000000',
    fontFamily: 'System',
    fontSize: { xs: 10, sm: 12, base: 14, md: 16, lg: 18, xl: 20, '2xl': 24, '3xl': 32 },
  },
  {
    id: 'dark-modern',
    name: 'Dark Modern',
    nameAr: '???????? ????????',
    primary: '#ffffff',
    secondary: '#a0a0a0',
    accent: '#cccccc',
    background: ['#1a1a1a', '#2a2a2a', '#1a1a1a'],
    surface: '#2a2a2a',
    text: '#ffffff',
    textSecondary: '#a0a0a0',
    border: '#404040',
    cardStyle: 'solid',
    buttonStyle: 'flat',
    borderGlow: false,
    blur: 0,
    iconStyle: 'filled',
    iconColor: '#ffffff',
    fontFamily: 'System',
    fontSize: { xs: 10, sm: 12, base: 14, md: 16, lg: 18, xl: 20, '2xl': 24, '3xl': 32 },
  },
  
  // Gold & Luxury Themes (3)
  {
    id: 'midnight-gold',
    name: 'Midnight Gold',
    nameAr: '?????? ?????????? ??????????',
    primary: '#ffd700',
    secondary: '#b8860b',
    accent: '#e6c200',
    background: ['#000408', '#1a1a0a', '#000408'],
    surface: '#1a1a0a',
    text: '#ffd700',
    textSecondary: '#b8860b',
    border: '#ffd700',
    cardStyle: 'solid',
    buttonStyle: '3d-glow',
    borderGlow: true,
    blur: 0,
    iconStyle: 'filled',
    iconColor: '#ffd700',
    fontFamily: 'System',
    fontSize: { xs: 10, sm: 12, base: 14, md: 16, lg: 18, xl: 20, '2xl': 24, '3xl': 32 },
  },
  {
    id: 'royal-gold',
    name: 'Royal Gold',
    nameAr: '?????? ????????',
    primary: '#d4af37',
    secondary: '#c9a961',
    accent: '#b8860b',
    background: ['#000000', '#0a0a0a', '#000000'],
    surface: '#0a0a0a',
    text: '#d4af37',
    textSecondary: '#c9a961',
    border: '#d4af37',
    cardStyle: 'solid',
    buttonStyle: '3d-glow',
    borderGlow: true,
    blur: 0,
    iconStyle: 'filled',
    iconColor: '#d4af37',
    fontFamily: 'System',
    fontSize: { xs: 10, sm: 12, base: 14, md: 16, lg: 18, xl: 20, '2xl': 24, '3xl': 32 },
  },
  {
    id: 'luxury-black',
    name: 'Luxury Black',
    nameAr: '???????? ????????',
    primary: '#d4af37',
    secondary: '#c9a961',
    accent: '#b8860b',
    background: ['#000000', '#0a0a0a', '#000000'],
    surface: '#0a0a0a',
    text: '#d4af37',
    textSecondary: '#c9a961',
    border: '#d4af37',
    cardStyle: 'solid',
    buttonStyle: '3d-glow',
    borderGlow: true,
    blur: 0,
    iconStyle: 'filled',
    iconColor: '#d4af37',
    fontFamily: 'System',
    fontSize: { xs: 10, sm: 12, base: 14, md: 16, lg: 18, xl: 20, '2xl': 24, '3xl': 32 },
  },
  
  // Nature Themes (5)
  {
    id: 'forest-green',
    name: 'Forest Green',
    nameAr: '???????? ????????????',
    primary: '#22c55e',
    secondary: '#16a34a',
    accent: '#15803d',
    background: ['#0a1a0a', '#1a2a1a', '#0a1a0a'],
    surface: '#1a2a1a',
    text: '#ffffff',
    textSecondary: '#22c55e',
    border: '#22c55e',
    cardStyle: 'solid',
    buttonStyle: 'flat',
    borderGlow: false,
    blur: 0,
    iconStyle: 'filled',
    iconColor: '#22c55e',
    fontFamily: 'System',
    fontSize: { xs: 10, sm: 12, base: 14, md: 16, lg: 18, xl: 20, '2xl': 24, '3xl': 32 },
  },
  {
    id: 'ocean-blue',
    name: 'Ocean Blue',
    nameAr: '???????? ????????????',
    primary: '#3b82f6',
    secondary: '#2563eb',
    accent: '#1d4ed8',
    background: ['#0a141a', '#1a2832', '#0a141a'],
    surface: '#1a2832',
    text: '#ffffff',
    textSecondary: '#3b82f6',
    border: '#3b82f6',
    cardStyle: 'solid',
    buttonStyle: 'flat',
    borderGlow: false,
    blur: 0,
    iconStyle: 'filled',
    iconColor: '#3b82f6',
    fontFamily: 'System',
    fontSize: { xs: 10, sm: 12, base: 14, md: 16, lg: 18, xl: 20, '2xl': 24, '3xl': 32 },
  },
  {
    id: 'sunset-orange',
    name: 'Sunset Orange',
    nameAr: '?????????????? ????????????',
    primary: '#f97316',
    secondary: '#ea580c',
    accent: '#c2410c',
    background: ['#1a0a00', '#2a1400', '#1a0a00'],
    surface: '#2a1400',
    text: '#ffffff',
    textSecondary: '#f97316',
    border: '#f97316',
    cardStyle: 'solid',
    buttonStyle: 'flat',
    borderGlow: false,
    blur: 0,
    iconStyle: 'filled',
    iconColor: '#f97316',
    fontFamily: 'System',
    fontSize: { xs: 10, sm: 12, base: 14, md: 16, lg: 18, xl: 20, '2xl': 24, '3xl': 32 },
  },
  {
    id: 'lavender-purple',
    name: 'Lavender Purple',
    nameAr: '???????????? ????????????????',
    primary: '#a78bfa',
    secondary: '#8b5cf6',
    accent: '#7c3aed',
    background: ['#1a0a1a', '#2a1a2a', '#1a0a1a'],
    surface: '#2a1a2a',
    text: '#ffffff',
    textSecondary: '#a78bfa',
    border: '#a78bfa',
    cardStyle: 'solid',
    buttonStyle: 'flat',
    borderGlow: false,
    blur: 0,
    iconStyle: 'filled',
    iconColor: '#a78bfa',
    fontFamily: 'System',
    fontSize: { xs: 10, sm: 12, base: 14, md: 16, lg: 18, xl: 20, '2xl': 24, '3xl': 32 },
  },
  {
    id: 'rose-pink',
    name: 'Rose Pink',
    nameAr: '???????? ??????????',
    primary: '#f43f5e',
    secondary: '#e11d48',
    accent: '#be123c',
    background: ['#1a0a0a', '#2a1a1a', '#1a0a0a'],
    surface: '#2a1a1a',
    text: '#ffffff',
    textSecondary: '#f43f5e',
    border: '#f43f5e',
    cardStyle: 'solid',
    buttonStyle: 'flat',
    borderGlow: false,
    blur: 0,
    iconStyle: 'filled',
    iconColor: '#f43f5e',
    fontFamily: 'System',
    fontSize: { xs: 10, sm: 12, base: 14, md: 16, lg: 18, xl: 20, '2xl': 24, '3xl': 32 },
  },
  
  // Professional Themes (3)
  {
    id: 'corporate-blue',
    name: 'Corporate Blue',
    nameAr: '???????? ??????????????',
    primary: '#2563eb',
    secondary: '#1d4ed8',
    accent: '#1e40af',
    background: ['#f8fafc', '#f1f5f9', '#f8fafc'],
    surface: '#ffffff',
    text: '#1e293b',
    textSecondary: '#64748b',
    border: '#cbd5e1',
    cardStyle: 'solid',
    buttonStyle: 'flat',
    borderGlow: false,
    blur: 0,
    iconStyle: 'outline',
    iconColor: '#2563eb',
    fontFamily: 'System',
    fontSize: { xs: 10, sm: 12, base: 14, md: 16, lg: 18, xl: 20, '2xl': 24, '3xl': 32 },
  },
  {
    id: 'business-gray',
    name: 'Business Gray',
    nameAr: '?????????? ??????????????',
    primary: '#475569',
    secondary: '#334155',
    accent: '#1e293b',
    background: ['#ffffff', '#f8fafc', '#ffffff'],
    surface: '#ffffff',
    text: '#1e293b',
    textSecondary: '#64748b',
    border: '#e2e8f0',
    cardStyle: 'solid',
    buttonStyle: 'flat',
    borderGlow: false,
    blur: 0,
    iconStyle: 'outline',
    iconColor: '#475569',
    fontFamily: 'System',
    fontSize: { xs: 10, sm: 12, base: 14, md: 16, lg: 18, xl: 20, '2xl': 24, '3xl': 32 },
  },
  {
    id: 'professional-dark',
    name: 'Professional Dark',
    nameAr: '???????? ??????????????',
    primary: '#64748b',
    secondary: '#475569',
    accent: '#334155',
    background: ['#1e293b', '#334155', '#1e293b'],
    surface: '#334155',
    text: '#ffffff',
    textSecondary: '#94a3b8',
    border: '#475569',
    cardStyle: 'solid',
    buttonStyle: 'flat',
    borderGlow: false,
    blur: 0,
    iconStyle: 'filled',
    iconColor: '#64748b',
    fontFamily: 'System',
    fontSize: { xs: 10, sm: 12, base: 14, md: 16, lg: 18, xl: 20, '2xl': 24, '3xl': 32 },
  },
  
  // Vibrant Themes (3)
  {
    id: 'vibrant-cyan',
    name: 'Vibrant Cyan',
    nameAr: '?????????? ????????',
    primary: '#06b6d4',
    secondary: '#0891b2',
    accent: '#0e7490',
    background: ['#0a141a', '#1a2832', '#0a141a'],
    surface: '#1a2832',
    text: '#ffffff',
    textSecondary: '#06b6d4',
    border: '#06b6d4',
    cardStyle: 'solid',
    buttonStyle: 'flat',
    borderGlow: false,
    blur: 0,
    iconStyle: 'filled',
    iconColor: '#06b6d4',
    fontFamily: 'System',
    fontSize: { xs: 10, sm: 12, base: 14, md: 16, lg: 18, xl: 20, '2xl': 24, '3xl': 32 },
  },
  {
    id: 'vibrant-magenta',
    name: 'Vibrant Magenta',
    nameAr: '?????????????? ????????',
    primary: '#d946ef',
    secondary: '#c026d3',
    accent: '#a21caf',
    background: ['#1a0a1a', '#2a1a2a', '#1a0a1a'],
    surface: '#2a1a2a',
    text: '#ffffff',
    textSecondary: '#d946ef',
    border: '#d946ef',
    cardStyle: 'solid',
    buttonStyle: 'flat',
    borderGlow: false,
    blur: 0,
    iconStyle: 'filled',
    iconColor: '#d946ef',
    fontFamily: 'System',
    fontSize: { xs: 10, sm: 12, base: 14, md: 16, lg: 18, xl: 20, '2xl': 24, '3xl': 32 },
  },
  {
    id: 'vibrant-yellow',
    name: 'Vibrant Yellow',
    nameAr: '???????? ????????',
    primary: '#eab308',
    secondary: '#ca8a04',
    accent: '#a16207',
    background: ['#1a1a0a', '#2a2a1a', '#1a1a0a'],
    surface: '#2a2a1a',
    text: '#ffffff',
    textSecondary: '#eab308',
    border: '#eab308',
    cardStyle: 'solid',
    buttonStyle: 'flat',
    borderGlow: false,
    blur: 0,
    iconStyle: 'filled',
    iconColor: '#eab308',
    fontFamily: 'System',
    fontSize: { xs: 10, sm: 12, base: 14, md: 16, lg: 18, xl: 20, '2xl': 24, '3xl': 32 },
  },
  
  // Monochrome Themes (3)
  {
    id: 'pure-white',
    name: 'Pure White',
    nameAr: '???????? ??????',
    primary: '#000000',
    secondary: '#333333',
    accent: '#666666',
    background: ['#ffffff', '#f5f5f5', '#ffffff'],
    surface: '#ffffff',
    text: '#000000',
    textSecondary: '#333333',
    border: '#e0e0e0',
    cardStyle: 'solid',
    buttonStyle: 'flat',
    borderGlow: false,
    blur: 0,
    iconStyle: 'outline',
    iconColor: '#000000',
    fontFamily: 'System',
    fontSize: { xs: 10, sm: 12, base: 14, md: 16, lg: 18, xl: 20, '2xl': 24, '3xl': 32 },
  },
  {
    id: 'pure-black',
    name: 'Pure Black',
    nameAr: '???????? ??????',
    primary: '#ffffff',
    secondary: '#cccccc',
    accent: '#999999',
    background: ['#000000', '#0a0a0a', '#000000'],
    surface: '#0a0a0a',
    text: '#ffffff',
    textSecondary: '#cccccc',
    border: '#333333',
    cardStyle: 'solid',
    buttonStyle: 'flat',
    borderGlow: false,
    blur: 0,
    iconStyle: 'filled',
    iconColor: '#ffffff',
    fontFamily: 'System',
    fontSize: { xs: 10, sm: 12, base: 14, md: 16, lg: 18, xl: 20, '2xl': 24, '3xl': 32 },
  },
  {
    id: 'grayscale',
    name: 'Grayscale',
    nameAr: '?????????? ??????????',
    primary: '#6b7280',
    secondary: '#4b5563',
    accent: '#374151',
    background: ['#f9fafb', '#f3f4f6', '#f9fafb'],
    surface: '#ffffff',
    text: '#1f2937',
    textSecondary: '#6b7280',
    border: '#e5e7eb',
    cardStyle: 'solid',
    buttonStyle: 'flat',
    borderGlow: false,
    blur: 0,
    iconStyle: 'outline',
    iconColor: '#6b7280',
    fontFamily: 'System',
    fontSize: { xs: 10, sm: 12, base: 14, md: 16, lg: 18, xl: 20, '2xl': 24, '3xl': 32 },
  },
  
  // Gradient Themes (4)
  {
    id: 'gradient-purple',
    name: 'Gradient Purple',
    nameAr: '???????? ????????????',
    primary: '#8b5cf6',
    secondary: '#ec4899',
    accent: '#7c3aed',
    background: ['#1a0a1a', '#2a1a2a', '#0a0a1a'],
    surface: '#2a1a2a',
    text: '#ffffff',
    textSecondary: '#8b5cf6',
    border: '#8b5cf6',
    cardStyle: 'gradient',
    buttonStyle: '3d-glow',
    borderGlow: true,
    blur: 0,
    iconStyle: 'filled',
    iconColor: '#8b5cf6',
    fontFamily: 'System',
    fontSize: { xs: 10, sm: 12, base: 14, md: 16, lg: 18, xl: 20, '2xl': 24, '3xl': 32 },
  },
  {
    id: 'gradient-blue',
    name: 'Gradient Blue',
    nameAr: '???????? ????????',
    primary: '#3b82f6',
    secondary: '#06b6d4',
    accent: '#2563eb',
    background: ['#0a141a', '#1a2832', '#0a1a2a'],
    surface: '#1a2832',
    text: '#ffffff',
    textSecondary: '#3b82f6',
    border: '#3b82f6',
    cardStyle: 'gradient',
    buttonStyle: '3d-glow',
    borderGlow: true,
    blur: 0,
    iconStyle: 'filled',
    iconColor: '#3b82f6',
    fontFamily: 'System',
    fontSize: { xs: 10, sm: 12, base: 14, md: 16, lg: 18, xl: 20, '2xl': 24, '3xl': 32 },
  },
  {
    id: 'gradient-orange',
    name: 'Gradient Orange',
    nameAr: '???????? ??????????????',
    primary: '#f97316',
    secondary: '#eab308',
    accent: '#ea580c',
    background: ['#1a0a00', '#2a1400', '#1a1a0a'],
    surface: '#2a1400',
    text: '#ffffff',
    textSecondary: '#f97316',
    border: '#f97316',
    cardStyle: 'gradient',
    buttonStyle: '3d-glow',
    borderGlow: true,
    blur: 0,
    iconStyle: 'filled',
    iconColor: '#f97316',
    fontFamily: 'System',
    fontSize: { xs: 10, sm: 12, base: 14, md: 16, lg: 18, xl: 20, '2xl': 24, '3xl': 32 },
  },
  {
    id: 'gradient-green',
    name: 'Gradient Green',
    nameAr: '???????? ????????',
    primary: '#22c55e',
    secondary: '#06b6d4',
    accent: '#16a34a',
    background: ['#0a1a0a', '#1a2a1a', '#0a1a2a'],
    surface: '#1a2a1a',
    text: '#ffffff',
    textSecondary: '#22c55e',
    border: '#22c55e',
    cardStyle: 'gradient',
    buttonStyle: '3d-glow',
    borderGlow: true,
    blur: 0,
    iconStyle: 'filled',
    iconColor: '#22c55e',
    fontFamily: 'System',
    fontSize: { xs: 10, sm: 12, base: 14, md: 16, lg: 18, xl: 20, '2xl': 24, '3xl': 32 },
  },
  
  // Retro Themes (3)
  {
    id: 'retro-80s',
    name: 'Retro 80s',
    nameAr: '?????????? ????????????????????',
    primary: '#ff0080',
    secondary: '#00ffff',
    accent: '#cc0066',
    background: ['#000000', '#1a0a1a', '#000000'],
    surface: '#1a0a1a',
    text: '#ffffff',
    textSecondary: '#ff0080',
    border: '#ff0080',
    cardStyle: 'solid',
    buttonStyle: '3d-glow',
    borderGlow: true,
    blur: 0,
    iconStyle: 'filled',
    iconColor: '#ff0080',
    fontFamily: 'System',
    fontSize: { xs: 10, sm: 12, base: 14, md: 16, lg: 18, xl: 20, '2xl': 24, '3xl': 32 },
  },
  {
    id: 'retro-90s',
    name: 'Retro 90s',
    nameAr: '?????????? ??????????????????',
    primary: '#ff6b00',
    secondary: '#00ff00',
    accent: '#cc5500',
    background: ['#000000', '#1a1a00', '#000000'],
    surface: '#1a1a00',
    text: '#ffffff',
    textSecondary: '#ff6b00',
    border: '#ff6b00',
    cardStyle: 'solid',
    buttonStyle: '3d-glow',
    borderGlow: true,
    blur: 0,
    iconStyle: 'filled',
    iconColor: '#ff6b00',
    fontFamily: 'System',
    fontSize: { xs: 10, sm: 12, base: 14, md: 16, lg: 18, xl: 20, '2xl': 24, '3xl': 32 },
  },
  {
    id: 'vintage-brown',
    name: 'Vintage Brown',
    nameAr: '?????? ????????',
    primary: '#8b4513',
    secondary: '#a0522d',
    accent: '#654321',
    background: ['#2a1a0a', '#3a2a1a', '#2a1a0a'],
    surface: '#3a2a1a',
    text: '#ffffff',
    textSecondary: '#d4a574',
    border: '#8b4513',
    cardStyle: 'solid',
    buttonStyle: 'flat',
    borderGlow: false,
    blur: 0,
    iconStyle: 'filled',
    iconColor: '#d4a574',
    fontFamily: 'System',
    fontSize: { xs: 10, sm: 12, base: 14, md: 16, lg: 18, xl: 20, '2xl': 24, '3xl': 32 },
  },
  
  // High Contrast Themes (2)
  {
    id: 'high-contrast',
    name: 'High Contrast',
    nameAr: '?????????? ????????',
    primary: '#ffffff',
    secondary: '#000000',
    accent: '#333333',
    background: ['#000000', '#1a1a1a', '#000000'],
    surface: '#1a1a1a',
    text: '#ffffff',
    textSecondary: '#ffffff',
    border: '#ffffff',
    cardStyle: 'solid',
    buttonStyle: 'flat',
    borderGlow: false,
    blur: 0,
    iconStyle: 'filled',
    iconColor: '#ffffff',
    fontFamily: 'System',
    fontSize: { xs: 10, sm: 12, base: 14, md: 16, lg: 18, xl: 20, '2xl': 24, '3xl': 32 },
  },
  {
    id: 'inverted',
    name: 'Inverted',
    nameAr: '??????????',
    primary: '#000000',
    secondary: '#ffffff',
    accent: '#cccccc',
    background: ['#ffffff', '#f5f5f5', '#ffffff'],
    surface: '#ffffff',
    text: '#000000',
    textSecondary: '#000000',
    border: '#000000',
    cardStyle: 'solid',
    buttonStyle: 'flat',
    borderGlow: false,
    blur: 0,
    iconStyle: 'outline',
    iconColor: '#000000',
    fontFamily: 'System',
    fontSize: { xs: 10, sm: 12, base: 14, md: 16, lg: 18, xl: 20, '2xl': 24, '3xl': 32 },
  },
  
  // Additional Themes (15+ to reach 50+)
  {
    id: 'space-dark',
    name: 'Space Dark',
    nameAr: '???????? ????????????',
    primary: '#6366f1',
    secondary: '#8b5cf6',
    accent: '#4f46e5',
    background: ['#000000', '#0a0a1a', '#000000'],
    surface: '#0a0a1a',
    text: '#ffffff',
    textSecondary: '#6366f1',
    border: '#6366f1',
    cardStyle: 'solid',
    buttonStyle: '3d-glow',
    borderGlow: true,
    blur: 0,
    iconStyle: 'filled',
    iconColor: '#6366f1',
    fontFamily: 'System',
    fontSize: { xs: 10, sm: 12, base: 14, md: 16, lg: 18, xl: 20, '2xl': 24, '3xl': 32 },
  },
  {
    id: 'matrix-green',
    name: 'Matrix Green',
    nameAr: '???????? ????????????????',
    primary: '#00ff41',
    secondary: '#00cc33',
    accent: '#00aa2a',
    background: ['#000000', '#001a00', '#000000'],
    surface: '#001a00',
    text: '#00ff41',
    textSecondary: '#00cc33',
    border: '#00ff41',
    cardStyle: 'solid',
    buttonStyle: '3d-glow',
    borderGlow: true,
    blur: 0,
    iconStyle: 'filled',
    iconColor: '#00ff41',
    fontFamily: 'System',
    fontSize: { xs: 10, sm: 12, base: 14, md: 16, lg: 18, xl: 20, '2xl': 24, '3xl': 32 },
  },
  {
    id: 'fire-red',
    name: 'Fire Red',
    nameAr: '???????? ??????????',
    primary: '#ff3333',
    secondary: '#ff6666',
    accent: '#cc0000',
    background: ['#1a0000', '#2a0000', '#1a0000'],
    surface: '#2a0000',
    text: '#ffffff',
    textSecondary: '#ff3333',
    border: '#ff3333',
    cardStyle: 'solid',
    buttonStyle: '3d-glow',
    borderGlow: true,
    blur: 0,
    iconStyle: 'filled',
    iconColor: '#ff3333',
    fontFamily: 'System',
    fontSize: { xs: 10, sm: 12, base: 14, md: 16, lg: 18, xl: 20, '2xl': 24, '3xl': 32 },
  },
  {
    id: 'ice-blue',
    name: 'Ice Blue',
    nameAr: '???????? ????????????',
    primary: '#00ccff',
    secondary: '#0099cc',
    accent: '#007799',
    background: ['#000a14', '#001a28', '#000a14'],
    surface: '#001a28',
    text: '#ffffff',
    textSecondary: '#00ccff',
    border: '#00ccff',
    cardStyle: 'solid',
    buttonStyle: 'flat',
    borderGlow: false,
    blur: 0,
    iconStyle: 'filled',
    iconColor: '#00ccff',
    fontFamily: 'System',
    fontSize: { xs: 10, sm: 12, base: 14, md: 16, lg: 18, xl: 20, '2xl': 24, '3xl': 32 },
  },
  {
    id: 'sunshine-yellow',
    name: 'Sunshine Yellow',
    nameAr: '???????? ??????????',
    primary: '#ffcc00',
    secondary: '#ff9900',
    accent: '#cc9900',
    background: ['#1a1a00', '#2a2a00', '#1a1a00'],
    surface: '#2a2a00',
    text: '#ffffff',
    textSecondary: '#ffcc00',
    border: '#ffcc00',
    cardStyle: 'solid',
    buttonStyle: 'flat',
    borderGlow: false,
    blur: 0,
    iconStyle: 'filled',
    iconColor: '#ffcc00',
    fontFamily: 'System',
    fontSize: { xs: 10, sm: 12, base: 14, md: 16, lg: 18, xl: 20, '2xl': 24, '3xl': 32 },
  },
  {
    id: 'mint-fresh',
    name: 'Mint Fresh',
    nameAr: '???????? ??????????????',
    primary: '#00ffaa',
    secondary: '#00cc88',
    accent: '#00aa66',
    background: ['#000a0a', '#001a1a', '#000a0a'],
    surface: '#001a1a',
    text: '#ffffff',
    textSecondary: '#00ffaa',
    border: '#00ffaa',
    cardStyle: 'solid',
    buttonStyle: 'flat',
    borderGlow: false,
    blur: 0,
    iconStyle: 'filled',
    iconColor: '#00ffaa',
    fontFamily: 'System',
    fontSize: { xs: 10, sm: 12, base: 14, md: 16, lg: 18, xl: 20, '2xl': 24, '3xl': 32 },
  },
  {
    id: 'coral-reef',
    name: 'Coral Reef',
    nameAr: '???????? ??????????????',
    primary: '#ff6b6b',
    secondary: '#ff8e8e',
    accent: '#cc5555',
    background: ['#1a0a0a', '#2a1a1a', '#1a0a0a'],
    surface: '#2a1a1a',
    text: '#ffffff',
    textSecondary: '#ff6b6b',
    border: '#ff6b6b',
    cardStyle: 'solid',
    buttonStyle: 'flat',
    borderGlow: false,
    blur: 0,
    iconStyle: 'filled',
    iconColor: '#ff6b6b',
    fontFamily: 'System',
    fontSize: { xs: 10, sm: 12, base: 14, md: 16, lg: 18, xl: 20, '2xl': 24, '3xl': 32 },
  },
  {
    id: 'sapphire-blue',
    name: 'Sapphire Blue',
    nameAr: '???????? ??????????????',
    primary: '#0066ff',
    secondary: '#0052cc',
    accent: '#003d99',
    background: ['#000a1a', '#001a2a', '#000a1a'],
    surface: '#001a2a',
    text: '#ffffff',
    textSecondary: '#0066ff',
    border: '#0066ff',
    cardStyle: 'solid',
    buttonStyle: 'flat',
    borderGlow: false,
    blur: 0,
    iconStyle: 'filled',
    iconColor: '#0066ff',
    fontFamily: 'System',
    fontSize: { xs: 10, sm: 12, base: 14, md: 16, lg: 18, xl: 20, '2xl': 24, '3xl': 32 },
  },
  {
    id: 'emerald-green',
    name: 'Emerald Green',
    nameAr: '???????? ????????????',
    primary: '#00cc66',
    secondary: '#009944',
    accent: '#007733',
    background: ['#000a0a', '#001a1a', '#000a0a'],
    surface: '#001a1a',
    text: '#ffffff',
    textSecondary: '#00cc66',
    border: '#00cc66',
    cardStyle: 'solid',
    buttonStyle: 'flat',
    borderGlow: false,
    blur: 0,
    iconStyle: 'filled',
    iconColor: '#00cc66',
    fontFamily: 'System',
    fontSize: { xs: 10, sm: 12, base: 14, md: 16, lg: 18, xl: 20, '2xl': 24, '3xl': 32 },
  },
  {
    id: 'ruby-red',
    name: 'Ruby Red',
    nameAr: '???????? ??????????????',
    primary: '#ff0033',
    secondary: '#cc0022',
    accent: '#990011',
    background: ['#1a0000', '#2a0000', '#1a0000'],
    surface: '#2a0000',
    text: '#ffffff',
    textSecondary: '#ff0033',
    border: '#ff0033',
    cardStyle: 'solid',
    buttonStyle: '3d-glow',
    borderGlow: true,
    blur: 0,
    iconStyle: 'filled',
    iconColor: '#ff0033',
    fontFamily: 'System',
    fontSize: { xs: 10, sm: 12, base: 14, md: 16, lg: 18, xl: 20, '2xl': 24, '3xl': 32 },
  },
  {
    id: 'amethyst-purple',
    name: 'Amethyst Purple',
    nameAr: '???????????? ????????????',
    primary: '#9966ff',
    secondary: '#7733cc',
    accent: '#552299',
    background: ['#1a0a1a', '#2a1a2a', '#1a0a1a'],
    surface: '#2a1a2a',
    text: '#ffffff',
    textSecondary: '#9966ff',
    border: '#9966ff',
    cardStyle: 'solid',
    buttonStyle: 'flat',
    borderGlow: false,
    blur: 0,
    iconStyle: 'filled',
    iconColor: '#9966ff',
    fontFamily: 'System',
    fontSize: { xs: 10, sm: 12, base: 14, md: 16, lg: 18, xl: 20, '2xl': 24, '3xl': 32 },
  },
  {
    id: 'amber-gold',
    name: 'Amber Gold',
    nameAr: '???????? ????????????????',
    primary: '#ffaa00',
    secondary: '#cc8800',
    accent: '#996600',
    background: ['#1a1400', '#2a1f00', '#1a1400'],
    surface: '#2a1f00',
    text: '#ffffff',
    textSecondary: '#ffaa00',
    border: '#ffaa00',
    cardStyle: 'solid',
    buttonStyle: '3d-glow',
    borderGlow: true,
    blur: 0,
    iconStyle: 'filled',
    iconColor: '#ffaa00',
    fontFamily: 'System',
    fontSize: { xs: 10, sm: 12, base: 14, md: 16, lg: 18, xl: 20, '2xl': 24, '3xl': 32 },
  },
  {
    id: 'pearl-white',
    name: 'Pearl White',
    nameAr: '???????? ????????????',
    primary: '#333333',
    secondary: '#666666',
    accent: '#999999',
    background: ['#ffffff', '#f5f5f5', '#ffffff'],
    surface: '#ffffff',
    text: '#333333',
    textSecondary: '#666666',
    border: '#e0e0e0',
    cardStyle: 'solid',
    buttonStyle: 'flat',
    borderGlow: false,
    blur: 0,
    iconStyle: 'outline',
    iconColor: '#333333',
    fontFamily: 'System',
    fontSize: { xs: 10, sm: 12, base: 14, md: 16, lg: 18, xl: 20, '2xl': 24, '3xl': 32 },
  },
  {
    id: 'obsidian-black',
    name: 'Obsidian Black',
    nameAr: '???????? ??????????',
    primary: '#cccccc',
    secondary: '#999999',
    accent: '#666666',
    background: ['#000000', '#0a0a0a', '#000000'],
    surface: '#0a0a0a',
    text: '#cccccc',
    textSecondary: '#999999',
    border: '#333333',
    cardStyle: 'solid',
    buttonStyle: 'flat',
    borderGlow: false,
    blur: 0,
    iconStyle: 'filled',
    iconColor: '#cccccc',
    fontFamily: 'System',
    fontSize: { xs: 10, sm: 12, base: 14, md: 16, lg: 18, xl: 20, '2xl': 24, '3xl': 32 },
  },
  {
    id: 'platinum-silver',
    name: 'Platinum Silver',
    nameAr: '?????? ????????????????',
    primary: '#888888',
    secondary: '#aaaaaa',
    accent: '#cccccc',
    background: ['#1a1a1a', '#2a2a2a', '#1a1a1a'],
    surface: '#2a2a2a',
    text: '#ffffff',
    textSecondary: '#aaaaaa',
    border: '#666666',
    cardStyle: 'solid',
    buttonStyle: 'flat',
    borderGlow: false,
    blur: 0,
    iconStyle: 'filled',
    iconColor: '#aaaaaa',
    fontFamily: 'System',
    fontSize: { xs: 10, sm: 12, base: 14, md: 16, lg: 18, xl: 20, '2xl': 24, '3xl': 32 },
  },
  
  // Additional Themes from existing config (3)
  {
    id: 'neumorphic',
    name: 'Neumorphic',
    nameAr: '??????????????????',
    primary: '#6C7CE7',
    secondary: '#FF8A65',
    accent: '#81C784',
    background: ['#E8ECF1', '#F0F4F8', '#E8ECF1'],
    surface: '#F5F7FA',
    text: '#2C3E50',
    textSecondary: '#7F8C8D',
    border: '#D5DBE1',
    cardStyle: 'neumorphic',
    buttonStyle: 'neumorphic',
    borderGlow: false,
    blur: 0,
    iconStyle: 'outline',
    iconColor: '#6C7CE7',
    fontFamily: 'System',
    fontSize: { xs: 10, sm: 12, base: 14, md: 16, lg: 18, xl: 20, '2xl': 24, '3xl': 32 },
  },
  {
    id: 'glassmorphism',
    name: 'Glassmorphism',
    nameAr: '???????? ??????????????',
    primary: '#4A90E2',
    secondary: '#E94B8B',
    accent: '#FFD700',
    background: ['#1E3A5F', '#2D4A6B', '#1E3A5F'],
    surface: 'rgba(255, 255, 255, 0.1)',
    text: '#FFFFFF',
    textSecondary: 'rgba(255, 255, 255, 0.7)',
    border: 'rgba(255, 255, 255, 0.2)',
    cardStyle: 'glass',
    buttonStyle: 'flat',
    borderGlow: false,
    blur: 20,
    iconStyle: 'filled',
    iconColor: '#FFFFFF',
    fontFamily: 'System',
    fontSize: { xs: 10, sm: 12, base: 14, md: 16, lg: 18, xl: 20, '2xl': 24, '3xl': 32 },
  },
  {
    id: 'dark-finance',
    name: 'Dark Finance',
    nameAr: '???????? ????????',
    primary: '#FF6B35',
    secondary: '#4ECDC4',
    accent: '#95E1D3',
    background: ['#0F1419', '#1A1F2E', '#0F1419'],
    surface: '#1E2532',
    text: '#FFFFFF',
    textSecondary: '#A0AEC0',
    border: '#2D3748',
    cardStyle: 'solid',
    buttonStyle: '3d-glow',
    borderGlow: true,
    blur: 0,
    iconStyle: 'filled',
    iconColor: '#FF6B35',
    fontFamily: 'System',
    fontSize: { xs: 10, sm: 12, base: 14, md: 16, lg: 18, xl: 20, '2xl': 24, '3xl': 32 },
  },
];

// Export default theme
export const DEFAULT_THEME = ALL_THEMES[0];


