@echo off
echo ========================================
echo تنظيف الملفات غير الضرورية
echo ========================================
echo.

REM حذف ملفات JSON المؤقتة (كانت للتجربة فقط)
echo حذف ملفات JSON المؤقتة...
del /Q "Create_Payment_Session_Tool.json" 2>nul
del /Q "Create_Payment_Session_Tool_FIXED.json" 2>nul
del /Q "Create_Payment_Session_Tool_AED.json" 2>nul
del /Q "Tool_JSON_الصحيح.json" 2>nul

REM حذف ملفات .md المؤقتة (تقارير الحالة القديمة)
echo حذف ملفات .md المؤقتة...
del /Q "*_STATUS.md" 2>nul
del /Q "*_COMPLETE.md" 2>nul
del /Q "*_VERIFICATION.md" 2>nul
del /Q "*_FIXED.md" 2>nul
del /Q "*_REPORT.md" 2>nul
del /Q "*_GUIDE.md" 2>nul
del /Q "*_SETUP.md" 2>nul
del /Q "*_FIX.md" 2>nul
del /Q "*_UPDATE.md" 2>nul
del /Q "*_SUMMARY.md" 2>nul
del /Q "*_CHECKLIST.md" 2>nul
del /Q "*_INSTRUCTIONS.md" 2>nul
del /Q "*_EXPLAINED.md" 2>nul
del /Q "*_WORKING.md" 2>nul
del /Q "*_READY.md" 2>nul
del /Q "*_STARTED.md" 2>nul
del /Q "*_PROGRESS.md" 2>nul
del /Q "*_BUILD.md" 2>nul
del /Q "*_ERRORS.md" 2>nul
del /Q "*_APPLIED.md" 2>nul
del /Q "*_QUICK.md" 2>nul
del /Q "*_NOW.md" 2>nul
del /Q "*_HERE.md" 2>nul
del /Q "*_SIMPLE.md" 2>nul
del /Q "*_REQUIRED.md" 2>nul
del /Q "*_COMPARISON.md" 2>nul
del /Q "*_CAPABILITIES.md" 2>nul
del /Q "*_ROADMAP.md" 2>nul
del /Q "*_PLANS.md" 2>nul
del /Q "*_EXECUTION.md" 2>nul
del /Q "*_SUBSCRIPTION.md" 2>nul
del /Q "*_ARCHITECTURE.md" 2>nul
del /Q "*_CONNECTION.md" 2>nul
del /Q "*_INTEGRATION.md" 2>nul
del /Q "*_ENHANCEMENTS.md" 2>nul
del /Q "*_DEPLOYMENT.md" 2>nul
del /Q "*_STANDALONE.md" 2>nul
del /Q "*_FLOW.md" 2>nul
del /Q "*_EXPLAINED.md" 2>nul
del /Q "*_COLLECTION.md" 2>nul
del /Q "*_ADDED.md" 2>nul
del /Q "*_FINAL.md" 2>nul
del /Q "*_COMPLETE.md" 2>nul
del /Q "*_VERIFIED.md" 2>nul
del /Q "*_STATUS.md" 2>nul
del /Q "*_KEYS.md" 2>nul
del /Q "*_INFO.md" 2>nul
del /Q "*_SERVICE.md" 2>nul
del /Q "*_WEBHOOK.md" 2>nul
del /Q "*_CREDENTIALS.md" 2>nul
del /Q "*_RECOVERY.md" 2>nul
del /Q "*_TEMPLATE.md" 2>nul
del /Q "*_TUNNEL.md" 2>nul
del /Q "*_QUICK_START.md" 2>nul
del /Q "*_HOW_TO.md" 2>nul
del /Q "*_STEP_BY_STEP.md" 2>nul
del /Q "*_TESTING.md" 2>nul
del /Q "*_PLAN.md" 2>nul
del /Q "*_RULES.md" 2>nul
del /Q "*_PATH.md" 2>nul
del /Q "*_OPTIMIZATION.md" 2>nul
del /Q "*_SYSTEM.md" 2>nul
del /Q "*_FEATURES.md" 2>nul
del /Q "*_IMPLEMENTATION.md" 2>nul
del /Q "*_BOOT.md" 2>nul
del /Q "*_SCREEN.md" 2>nul
del /Q "*_THEMES.md" 2>nul
del /Q "*_SPLASH.md" 2>nul
del /Q "*_FIXES.md" 2>nul
del /Q "*_CHECKS.md" 2>nul
del /Q "*_COMMANDS.md" 2>nul
del /Q "*_CONFIG.md" 2>nul
del /Q "*_NUMBER.md" 2>nul
del /Q "*_INCREASED.md" 2>nul
del /Q "*_UPDATED.md" 2>nul
del /Q "*_VERSION.md" 2>nul
del /Q "*_NEW.md" 2>nul
del /Q "*_PHASE.md" 2>nul
del /Q "*_REQUIREMENTS.md" 2>nul
del /Q "*_POWERSHELL.md" 2>nul
del /Q "*_COMMANDS.md" 2>nul
del /Q "*_PRE.md" 2>nul
del /Q "*_PUSH.md" 2>nul
del /Q "*_REPO.md" 2>nul
del /Q "*_INFO.md" 2>nul
del /Q "*_AND.md" 2>nul
del /Q "*_SUCCESS.md" 2>nul
del /Q "*_GIT.md" 2>nul
del /Q "*_CLOUDFLARE.md" 2>nul
del /Q "*_EXPLANATION.md" 2>nul
del /Q "*_SEE.md" 2>nul
del /Q "*_QR.md" 2>nul
del /Q "*_CODE.md" 2>nul
del /Q "*_VIEW.md" 2>nul
del /Q "*_EAS.md" 2>nul
del /Q "*_SECRETS.md" 2>nul
del /Q "*_VARIABLES.md" 2>nul
del /Q "*_ENV.md" 2>nul
del /Q "*_TRANSFER.md" 2>nul
del /Q "*_ONLY.md" 2>nul
del /Q "*_AUTHORITY.md" 2>nul
del /Q "*_LAYER.md" 2>nul
del /Q "*_COGNITIVE.md" 2>nul
del /Q "*_ARCHITECTURE.md" 2>nul
del /Q "*_REPORT.md" 2>nul
del /Q "*_MISSING.md" 2>nul
del /Q "*_BACKEND.md" 2>nul
del /Q "*_ITEMS.md" 2>nul
del /Q "*_VS.md" 2>nul
del /Q "*_CLAIMS.md" 2>nul
del /Q "*_VERIFICATION.md" 2>nul
del /Q "*_TRUTH.md" 2>nul
del /Q "*_ONLY.md" 2>nul
del /Q "*_FINAL.md" 2>nul
del /Q "*_REPORT.md" 2>nul
del /Q "*_HONEST.md" 2>nul
del /Q "*_DEEP.md" 2>nul
del /Q "*_ANALYSIS.md" 2>nul
del /Q "*_FILE.md" 2>nul
del /Q "*_VERIFICATION.md" 2>nul
del /Q "*_FEATURES.md" 2>nul
del /Q "*_STATUS.md" 2>nul
del /Q "*_QUICK.md" 2>nul
del /Q "*_START.md" 2>nul
del /Q "*_SERVICES.md" 2>nul
del /Q "*_GUIDE.md" 2>nul
del /Q "*_OPTIMIZATION.md" 2>nul
del /Q "*_COMPLETE.md" 2>nul
del /Q "*_SYSTEM.md" 2>nul
del /Q "*_VERIFICATION.md" 2>nul
del /Q "*_COMPLETE.md" 2>nul
del /Q "*_VERIFY.md" 2>nul
del /Q "*_SYSTEM.md" 2>nul
del /Q "*_COMPREHENSIVE.md" 2>nul
del /Q "*_REPORT.md" 2>nul
del /Q "*_FINAL.md" 2>nul
del /Q "*_REPORT.md" 2>nul
del /Q "*_SYSTEM.md" 2>nul
del /Q "*_STATUS.md" 2>nul
del /Q "*_SETUP.md" 2>nul
del /Q "*_INSTRUCTIONS.md" 2>nul
del /Q "*_README.md" 2>nul
del /Q "*_START.md" 2>nul
del /Q "*_HERE.md" 2>nul
del /Q "*_ABSOLUTE.md" 2>nul
del /Q "*_RULE.md" 2>nul
del /Q "*_BUILD.md" 2>nul
del /Q "*_IN.md" 2>nul
del /Q "*_PROGRESS.md" 2>nul
del /Q "*_COMPLETE.md" 2>nul
del /Q "*_SYSTEM.md" 2>nul
del /Q "*_BUILD.md" 2>nul
del /Q "*_COMPREHENSIVE.md" 2>nul
del /Q "*_VERIFICATION.md" 2>nul
del /Q "*_PROGRESS.md" 2>nul
del /Q "*_SUMMARY.md" 2>nul
del /Q "*_SYSTEM.md" 2>nul
del /Q "*_BUILD.md" 2>nul
del /Q "*_STATUS.md" 2>nul
del /Q "*_VERIFICATION.md" 2>nul
del /Q "*_VS.md" 2>nul
del /Q "*_CLAIMS.md" 2>nul
del /Q "*_ARCHITECTURE.md" 2>nul
del /Q "*_FIX.md" 2>nul
del /Q "*_PLAN.md" 2>nul
del /Q "*_CONNECTION.md" 2>nul
del /Q "*_STATUS.md" 2>nul
del /Q "*_FINAL.md" 2>nul
del /Q "*_STATUS.md" 2>nul
del /Q "*_FIXED.md" 2>nul
del /Q "*_WORKING.md" 2>nul
del /Q "*_HERE.md" 2>nul
del /Q "*_MOBILE.md" 2>nul
del /Q "*_MISSING.md" 2>nul
del /Q "*_IN.md" 2>nul
del /Q "*_BOOT.md" 2>nul
del /Q "*_LOGIN.md" 2>nul
del /Q "*_HOME.md" 2>nul
del /Q "*_BACKEND.md" 2>nul
del /Q "*_DOMAIN.md" 2>nul
del /Q "*_SETUP.md" 2>nul
del /Q "*_INSTRUCTIONS.md" 2>nul
del /Q "*_LOCAL.md" 2>nul
del /Q "*_VS.md" 2>nul
del /Q "*_CLOUD.md" 2>nul
del /Q "*_COMPARISON.md" 2>nul
del /Q "*_QUICK.md" 2>nul
del /Q "*_START.md" 2>nul
del /Q "*_KERNEL.md" 2>nul
del /Q "*_AUTHORITY.md" 2>nul
del /Q "*_LAYER.md" 2>nul
del /Q "*_VERIFICATION.md" 2>nul
del /Q "*_REPORT.md" 2>nul
del /Q "*_COMPLETE.md" 2>nul
del /Q "*_BOOT.md" 2>nul
del /Q "*_IMPLEMENTATION.md" 2>nul
del /Q "*_SCREEN.md" 2>nul
del /Q "*_IMPLEMENTATION.md" 2>nul
del /Q "*_COMPLETE.md" 2>nul
del /Q "*_STATUS.md" 2>nul
del /Q "*_REPORT.md" 2>nul
del /Q "*_PROJECT.md" 2>nul
del /Q "*_STATUS.md" 2>nul
del /Q "*_SUMMARY.md" 2>nul
del /Q "*_WORKING.md" 2>nul
del /Q "*_RULES.md" 2>nul
del /Q "*_ARCHITECTURE.md" 2>nul
del /Q "*_INTEGRATION.md" 2>nul
del /Q "*_REQUIRED.md" 2>nul
del /Q "*_API.md" 2>nul
del /Q "*_KEYS.md" 2>nul
del /Q "*_ADDED.md" 2>nul
del /Q "*_IMPLEMENTATION.md" 2>nul
del /Q "*_STATUS.md" 2>nul
del /Q "*_LOYALTY.md" 2>nul
del /Q "*_INTEGRATION.md" 2>nul
del /Q "*_VERIFICATION.md" 2>nul
del /Q "*_MAPS.md" 2>nul
del /Q "*_ROUTES.md" 2>nul
del /Q "*_COMPLETE.md" 2>nul
del /Q "*_PHASE.md" 2>nul
del /Q "*_0.md" 2>nul
del /Q "*_MAPS.md" 2>nul
del /Q "*_REQUIREMENTS.md" 2>nul
del /Q "*_PROJECT.md" 2>nul
del /Q "*_PATH.md" 2>nul
del /Q "*_SYSTEMS.md" 2>nul
del /Q "*_VERIFICATION.md" 2>nul
del /Q "*_SYSTEMS.md" 2>nul
del /Q "*_AND.md" 2>nul
del /Q "*_SCREENS.md" 2>nul
del /Q "*_UI.md" 2>nul
del /Q "*_IMPROVEMENTS.md" 2>nul
del /Q "*_APPLIED.md" 2>nul
del /Q "*_WEATHERKIT.md" 2>nul
del /Q "*_CREDENTIALS.md" 2>nul
del /Q "*_ADDED.md" 2>nul
del /Q "*_README.md" 2>nul
del /Q "*_WEB.md" 2>nul
del /Q "*_FINAL.md" 2>nul
del /Q "*_FIX.md" 2>nul
del /Q "*_WEB.md" 2>nul
del /Q "*_FIX.md" 2>nul
del /Q "*_COMPLETE.md" 2>nul
del /Q "*_WEB.md" 2>nul
del /Q "*_SIMPLE.md" 2>nul
del /Q "*_FIX.md" 2>nul
del /Q "*_WEB.md" 2>nul
del /Q "*_START.md" 2>nul
del /Q "*_NOW.md" 2>nul
del /Q "*_Webhook.md" 2>nul
del /Q "*_Secret.md" 2>nul
del /Q "*_تم.md" 2>nul
del /Q "*_الحفظ.md" 2>nul
del /Q "*_الأحداث.md" 2>nul
del /Q "*_المتاحة.md" 2>nul
del /Q "*_في.md" 2>nul
del /Q "*_Webhook.md" 2>nul
del /Q "*_الفرق.md" 2>nul
del /Q "*_بين.md" 2>nul
del /Q "*_Documentation.md" 2>nul
del /Q "*_و.md" 2>nul
del /Q "*_Script.md" 2>nul
del /Q "*_شرح.md" 2>nul
del /Q "*_واجهة.md" 2>nul
del /Q "*_Agent.md" 2>nul
del /Q "*_Tools.md" 2>nul
del /Q "*_كيف.md" 2>nul
del /Q "*_تملأ.md" 2>nul
del /Q "*_Webhook.md" 2>nul
del /Q "*_في.md" 2>nul
del /Q "*_ElevenLabs.md" 2>nul
del /Q "*_ربط.md" 2>nul
del /Q "*_الباك.md" 2>nul
del /Q "*_اند.md" 2>nul
del /Q "*_مع.md" 2>nul
del /Q "*_ElevenLabs.md" 2>nul
del /Q "*_خطوات.md" 2>nul
del /Q "*_الربط.md" 2>nul
del /Q "*_قبل.md" 2>nul
del /Q "*_تشغيل.md" 2>nul
del /Q "*_Script.md" 2>nul
del /Q "*_شغل.md" 2>nul
del /Q "*_Script.md" 2>nul
del /Q "*_الآن.md" 2>nul
del /Q "*_إضافة.md" 2>nul
del /Q "*_Tools.md" 2>nul
del /Q "*_باستخدام.md" 2>nul
del /Q "*_API.md" 2>nul
del /Q "*_كيف.md" 2>nul
del /Q "*_تعمل.md" 2>nul
del /Q "*_كل.md" 2>nul
del /Q "*_حاجة.md" 2>nul
del /Q "*_خطوة.md" 2>nul
del /Q "*_بخطوة.md" 2>nul
del /Q "*_خطة.md" 2>nul
del /Q "*_الإعداد.md" 2>nul
del /Q "*_السريعة.md" 2>nul
del /Q "*_إعداد.md" 2>nul
del /Q "*_Agent.md" 2>nul
del /Q "*_بسرعة.md" 2>nul
del /Q "*_باستخدام.md" 2>nul
del /Q "*_API.md" 2>nul
del /Q "*_ربط.md" 2>nul
del /Q "*_Tools.md" 2>nul
del /Q "*_مع.md" 2>nul
del /Q "*_Workflow.md" 2>nul
del /Q "*_في.md" 2>nul
del /Q "*_ElevenLabs.md" 2>nul
del /Q "*_إصلاح.md" 2>nul
del /Q "*_العملة.md" 2>nul
del /Q "*_و.md" 2>nul
del /Q "*_Client.md" 2>nul
del /Q "*_ID.md" 2>nul
del /Q "*_كيف.md" 2>nul
del /Q "*_تختبر.md" 2>nul
del /Q "*_Tool.md" 2>nul
del /Q "*_الخطوات.md" 2>nul
del /Q "*_التالية.md" 2>nul
del /Q "*_بعد.md" 2>nul
del /Q "*_إضافة.md" 2>nul
del /Q "*_Tool.md" 2>nul
del /Q "*_إصلاح.md" 2>nul
del /Q "*_أخطاء.md" 2>nul
del /Q "*_JSON.md" 2>nul
del /Q "*_إصلاح.md" 2>nul
del /Q "*_Tool.md" 2>nul
del /Q "*_JSON.md" 2>nul
del /Q "*_إعداد.md" 2>nul
del /Q "*_Body.md" 2>nul
del /Q "*_Parameters.md" 2>nul
del /Q "*_صحيح.md" 2>nul
del /Q "*_كيف.md" 2>nul
del /Q "*_تكتب.md" 2>nul
del /Q "*_Header.md" 2>nul
del /Q "*_صحيح.md" 2>nul
del /Q "*_خطوات.md" 2>nul
del /Q "*_إضافة.md" 2>nul
del /Q "*_Tool.md" 2>nul
del /Q "*_بعد.md" 2>nul
del /Q "*_Headers.md" 2>nul
del /Q "*_كيف.md" 2>nul
del /Q "*_تضيف.md" 2>nul
del /Q "*_Tools.md" 2>nul
del /Q "*_في.md" 2>nul
del /Q "*_Dashboard.md" 2>nul
del /Q "*_ماذا.md" 2>nul
del /Q "*_تفعل.md" 2>nul
del /Q "*_الآن.md" 2>nul
del /Q "*_إصلاح.md" 2>nul
del /Q "*_العملة.md" 2>nul
del /Q "*_و.md" 2>nul
del /Q "*_Client.md" 2>nul
del /Q "*_ID.md" 2>nul

REM حذف ملفات .txt المؤقتة
echo حذف ملفات .txt المؤقتة...
del /Q "backend\temp_env.txt" 2>nul

REM حذف ملفات .bat المكررة (الاحتفاظ بالأساسية فقط)
echo حذف ملفات .bat المكررة...
del /Q "CLEANUP_FILES.bat" 2>nul

echo.
echo ========================================
echo تم التنظيف بنجاح!
echo ========================================
echo.
echo الملفات المهمة المحفوظة:
echo - README.md
echo - الخطة_النهائية_للتطبيق_المستقبلي.md
echo - COPY_TO_EAS.txt
echo - UPDATE_BACKEND_ENV.bat
echo - setup_elevenlabs_agent.js
echo - ALL_TOOLS_READY_FOR_COPY.json
echo.
pause


